//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.16 at 10:40:22 AM CEST 
//


package org.taktik.connector.business.medadminurses.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CareReceiverIdType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CareReceiverIdType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Inss" type="{urn:be:cin:mycarenet:1.0:carenet:types}InssType" minOccurs="0"/>
 *         &lt;element name="RegNrWithMut" type="{urn:be:cin:mycarenet:1.0:carenet:types}RegNrWithMutType" minOccurs="0"/>
 *         &lt;element name="Mutuality" type="{urn:be:cin:mycarenet:1.0:carenet:types}MutualityType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CareReceiverIdType", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", propOrder = {
    "inss",
    "regNrWithMut",
    "mutuality"
})
public class CareReceiverIdType {

    @XmlElement(name = "Inss", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    protected String inss;
    @XmlElement(name = "RegNrWithMut", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    protected String regNrWithMut;
    @XmlElement(name = "Mutuality", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    protected String mutuality;

    /**
     * Gets the value of the inss property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInss() {
        return inss;
    }

    /**
     * Sets the value of the inss property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInss(String value) {
        this.inss = value;
    }

    /**
     * Gets the value of the regNrWithMut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegNrWithMut() {
        return regNrWithMut;
    }

    /**
     * Sets the value of the regNrWithMut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegNrWithMut(String value) {
        this.regNrWithMut = value;
    }

    /**
     * Gets the value of the mutuality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMutuality() {
        return mutuality;
    }

    /**
     * Sets the value of the mutuality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMutuality(String value) {
        this.mutuality = value;
    }

}
