//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.16 at 10:40:22 AM CEST 
//


package org.taktik.connector.business.medadminurses.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CarePlaceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CarePlaceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CarePlaceName" type="{urn:be:cin:mycarenet:1.0:carenet:types}String_25"/>
 *         &lt;element name="CarePlaceAdress" type="{urn:be:cin:mycarenet:1.0:carenet:types}String_25"/>
 *         &lt;element name="CarePlacePostalCode" type="{urn:be:cin:mycarenet:1.0:carenet:types}PostalCodeType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CarePlaceType", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", propOrder = {
    "carePlaceName",
    "carePlaceAdress",
    "carePlacePostalCode"
})
public class CarePlaceType {

    @XmlElement(name = "CarePlaceName", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected String carePlaceName;
    @XmlElement(name = "CarePlaceAdress", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected String carePlaceAdress;
    @XmlElement(name = "CarePlacePostalCode", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected String carePlacePostalCode;

    /**
     * Gets the value of the carePlaceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarePlaceName() {
        return carePlaceName;
    }

    /**
     * Sets the value of the carePlaceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarePlaceName(String value) {
        this.carePlaceName = value;
    }

    /**
     * Gets the value of the carePlaceAdress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarePlaceAdress() {
        return carePlaceAdress;
    }

    /**
     * Sets the value of the carePlaceAdress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarePlaceAdress(String value) {
        this.carePlaceAdress = value;
    }

    /**
     * Gets the value of the carePlacePostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarePlacePostalCode() {
        return carePlacePostalCode;
    }

    /**
     * Sets the value of the carePlacePostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarePlacePostalCode(String value) {
        this.carePlacePostalCode = value;
    }

}
