//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.16 at 10:40:22 AM CEST 
//


package org.taktik.connector.business.medadminurses.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContractualTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ContractualTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="A"/>
 *     &lt;enumeration value="B"/>
 *     &lt;enumeration value="C"/>
 *     &lt;enumeration value="toilet"/>
 *     &lt;enumeration value="nomenclature"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ContractualTypeType", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
@XmlEnum
public enum ContractualTypeType {

    A("A"),
    B("B"),
    C("C"),
    @XmlEnumValue("toilet")
    TOILET("toilet"),
    @XmlEnumValue("nomenclature")
    NOMENCLATURE("nomenclature");
    private final String value;

    ContractualTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ContractualTypeType fromValue(String v) {
        for (ContractualTypeType c: ContractualTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
