//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.16 at 10:40:22 AM CEST 
//


package org.taktik.connector.business.medadminurses.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			     The Decision type is used to express the result of a decision done 
 * 			     by the Consultant Doctor.
 *             
 * 
 * <p>Java class for DecisionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DecisionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Reference" type="{urn:be:cin:mycarenet:1.0:carenet:types}DecisionReferenceType"/>
 *         &lt;element name="Reason" type="{urn:be:cin:mycarenet:1.0:carenet:types}RejectionReasonType" minOccurs="0"/>
 *         &lt;element name="Justification" type="{urn:be:cin:mycarenet:1.0:carenet:types}String_150" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="result" use="required" type="{urn:be:cin:mycarenet:1.0:carenet:types}DecisionResultType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DecisionType", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", propOrder = {
    "reference",
    "reason",
    "justification"
})
public class DecisionType {

    @XmlElement(name = "Reference", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected String reference;
    @XmlElement(name = "Reason", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    protected String reason;
    @XmlElement(name = "Justification", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    protected String justification;
    @XmlAttribute(name = "result", required = true)
    protected DecisionResultType result;

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReference(String value) {
        this.reference = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReason(String value) {
        this.reason = value;
    }

    /**
     * Gets the value of the justification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJustification() {
        return justification;
    }

    /**
     * Sets the value of the justification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJustification(String value) {
        this.justification = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link DecisionResultType }
     *     
     */
    public DecisionResultType getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link DecisionResultType }
     *     
     */
    public void setResult(DecisionResultType value) {
        this.result = value;
    }

}
