//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.16 at 10:40:22 AM CEST 
//


package org.taktik.connector.business.medadminurses.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			     Extension of the CareReceiverType used to identified the Care Receiver in the 4XXXXX messages
 *             	
 * 
 * <p>Java class for ExtCareReceiverStrictIdType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtCareReceiverStrictIdType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:be:cin:mycarenet:1.0:carenet:types}CareReceiverStrictIdType">
 *       &lt;sequence>
 *         &lt;element name="Sex" type="{urn:be:cin:mycarenet:1.0:carenet:types}SexType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtCareReceiverStrictIdType", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", propOrder = {
    "sex"
})
public class ExtCareReceiverStrictIdType
    extends CareReceiverStrictIdType
{

    @XmlElement(name = "Sex", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    @XmlSchemaType(name = "string")
    protected SexType sex;

    /**
     * Gets the value of the sex property.
     * 
     * @return
     *     possible object is
     *     {@link SexType }
     *     
     */
    public SexType getSex() {
        return sex;
    }

    /**
     * Sets the value of the sex property.
     * 
     * @param value
     *     allowed object is
     *     {@link SexType }
     *     
     */
    public void setSex(SexType value) {
        this.sex = value;
    }

}
