//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.16 at 10:40:22 AM CEST 
//


package org.taktik.connector.business.medadminurses.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KatzType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KatzType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="KatzScore" type="{urn:be:cin:mycarenet:1.0:carenet:types}KatzScoreType"/>
 *         &lt;element name="ContinenceDetails" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Dementia" type="{urn:be:cin:mycarenet:1.0:carenet:types}DementiaType" minOccurs="0"/>
 *         &lt;element name="Prescripter" type="{urn:be:cin:mycarenet:1.0:carenet:types}NihiiType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KatzType", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", propOrder = {
    "katzScore",
    "continenceDetails",
    "dementia",
    "prescripter"
})
public class KatzType {

    @XmlList
    @XmlElement(name = "KatzScore", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", type = Integer.class)
    protected List<Integer> katzScore;
    @XmlElement(name = "ContinenceDetails", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", defaultValue = "false")
    protected boolean continenceDetails;
    @XmlElement(name = "Dementia", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    protected DementiaType dementia;
    @XmlElement(name = "Prescripter", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    protected String prescripter;

    /**
     * Gets the value of the katzScore property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the katzScore property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKatzScore().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getKatzScore() {
        if (katzScore == null) {
            katzScore = new ArrayList<Integer>();
        }
        return this.katzScore;
    }

    /**
     * Gets the value of the continenceDetails property.
     * 
     */
    public boolean isContinenceDetails() {
        return continenceDetails;
    }

    /**
     * Sets the value of the continenceDetails property.
     * 
     */
    public void setContinenceDetails(boolean value) {
        this.continenceDetails = value;
    }

    /**
     * Gets the value of the dementia property.
     * 
     * @return
     *     possible object is
     *     {@link DementiaType }
     *     
     */
    public DementiaType getDementia() {
        return dementia;
    }

    /**
     * Sets the value of the dementia property.
     * 
     * @param value
     *     allowed object is
     *     {@link DementiaType }
     *     
     */
    public void setDementia(DementiaType value) {
        this.dementia = value;
    }

    /**
     * Gets the value of the prescripter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrescripter() {
        return prescripter;
    }

    /**
     * Sets the value of the prescripter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrescripter(String value) {
        this.prescripter = value;
    }

}
