//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.16 at 10:40:22 AM CEST 
//


package org.taktik.connector.business.medadminurses.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MedAdminResponseListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MedAdminResponseListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{urn:be:cin:mycarenet:1.0:carenet:types}SingleNurseContractualCareResponse"/>
 *         &lt;element ref="{urn:be:cin:mycarenet:1.0:carenet:types}SingleNurseContractualCareUpdate"/>
 *         &lt;element ref="{urn:be:cin:mycarenet:1.0:carenet:types}SinglePalliativeCareResponse"/>
 *         &lt;element ref="{urn:be:cin:mycarenet:1.0:carenet:types}SingleSpecificTechnicalCareResponse"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MedAdminResponseListType", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", propOrder = {
    "singleNurseContractualCareResponseOrSingleNurseContractualCareUpdateOrSinglePalliativeCareResponse"
})
public class MedAdminResponseListType {

    @XmlElements({
        @XmlElement(name = "SingleNurseContractualCareResponse", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", type = SingleNurseContractualCareResponseType.class),
        @XmlElement(name = "SingleNurseContractualCareUpdate", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", type = SingleNurseContractualCareUpdateType.class),
        @XmlElement(name = "SinglePalliativeCareResponse", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", type = SinglePalliativeCareResponseType.class),
        @XmlElement(name = "SingleSpecificTechnicalCareResponse", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", type = SingleSpecificTechnicalCareResponseType.class)
    })
    protected List<Object> singleNurseContractualCareResponseOrSingleNurseContractualCareUpdateOrSinglePalliativeCareResponse;

    /**
     * Gets the value of the singleNurseContractualCareResponseOrSingleNurseContractualCareUpdateOrSinglePalliativeCareResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the singleNurseContractualCareResponseOrSingleNurseContractualCareUpdateOrSinglePalliativeCareResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSingleNurseContractualCareResponseOrSingleNurseContractualCareUpdateOrSinglePalliativeCareResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SingleNurseContractualCareResponseType }
     * {@link SingleNurseContractualCareUpdateType }
     * {@link SinglePalliativeCareResponseType }
     * {@link SingleSpecificTechnicalCareResponseType }
     * 
     * 
     */
    public List<Object> getSingleNurseContractualCareResponseOrSingleNurseContractualCareUpdateOrSinglePalliativeCareResponse() {
        if (singleNurseContractualCareResponseOrSingleNurseContractualCareUpdateOrSinglePalliativeCareResponse == null) {
            singleNurseContractualCareResponseOrSingleNurseContractualCareUpdateOrSinglePalliativeCareResponse = new ArrayList<Object>();
        }
        return this.singleNurseContractualCareResponseOrSingleNurseContractualCareUpdateOrSinglePalliativeCareResponse;
    }

}
