//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.16 at 10:40:22 AM CEST 
//


package org.taktik.connector.business.medadminurses.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MessageNameType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MessageNameType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="M801000"/>
 *     &lt;enumeration value="M801000ERR"/>
 *     &lt;enumeration value="M801001"/>
 *     &lt;enumeration value="M801900"/>
 *     &lt;enumeration value="M410000"/>
 *     &lt;enumeration value="M410001"/>
 *     &lt;enumeration value="M410000ERR"/>
 *     &lt;enumeration value="M410900"/>
 *     &lt;enumeration value="M410908"/>
 *     &lt;enumeration value="M410999"/>
 *     &lt;enumeration value="M420000"/>
 *     &lt;enumeration value="M420001"/>
 *     &lt;enumeration value="M420000ERR"/>
 *     &lt;enumeration value="M420900"/>
 *     &lt;enumeration value="M420999"/>
 *     &lt;enumeration value="M430000"/>
 *     &lt;enumeration value="M430001"/>
 *     &lt;enumeration value="M430000ERR"/>
 *     &lt;enumeration value="M891000"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MessageNameType", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
@XmlEnum
public enum MessageNameType {

    @XmlEnumValue("M801000")
    M_801000("M801000"),
    @XmlEnumValue("M801000ERR")
    M_801000_ERR("M801000ERR"),
    @XmlEnumValue("M801001")
    M_801001("M801001"),
    @XmlEnumValue("M801900")
    M_801900("M801900"),
    @XmlEnumValue("M410000")
    M_410000("M410000"),
    @XmlEnumValue("M410001")
    M_410001("M410001"),
    @XmlEnumValue("M410000ERR")
    M_410000_ERR("M410000ERR"),
    @XmlEnumValue("M410900")
    M_410900("M410900"),
    @XmlEnumValue("M410908")
    M_410908("M410908"),
    @XmlEnumValue("M410999")
    M_410999("M410999"),
    @XmlEnumValue("M420000")
    M_420000("M420000"),
    @XmlEnumValue("M420001")
    M_420001("M420001"),
    @XmlEnumValue("M420000ERR")
    M_420000_ERR("M420000ERR"),
    @XmlEnumValue("M420900")
    M_420900("M420900"),
    @XmlEnumValue("M420999")
    M_420999("M420999"),
    @XmlEnumValue("M430000")
    M_430000("M430000"),
    @XmlEnumValue("M430001")
    M_430001("M430001"),
    @XmlEnumValue("M430000ERR")
    M_430000_ERR("M430000ERR"),
    @XmlEnumValue("M891000")
    M_891000("M891000");
    private final String value;

    MessageNameType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MessageNameType fromValue(String v) {
        for (MessageNameType c: MessageNameType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
