//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.16 at 10:40:22 AM CEST 
//


package org.taktik.connector.business.medadminurses.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MessageFaultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MessageFaultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FaultCode" type="{urn:be:cin:mycarenet:1.0:carenet:types}FaultCodeType"/>
 *         &lt;element name="FaultSource" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MultiIO" type="{urn:be:cin:mycarenet:1.0:carenet:types}MultiIOType" minOccurs="0"/>
 *         &lt;element name="Message" type="{urn:be:cin:mycarenet:1.0:carenet:types}MessageType"/>
 *         &lt;element name="Details" type="{urn:be:cin:mycarenet:1.0:carenet:types}DetailsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageFaultType", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", propOrder = {
    "faultCode",
    "faultSource",
    "multiIO",
    "message",
    "details"
})
public class MessageFaultType {

    @XmlElement(name = "FaultCode", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    @XmlSchemaType(name = "string")
    protected FaultCodeType faultCode;
    @XmlElement(name = "FaultSource", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected String faultSource;
    @XmlElement(name = "MultiIO", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    protected MultiIOType multiIO;
    @XmlElement(name = "Message", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected MessageType message;
    @XmlElement(name = "Details", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected DetailsType details;

    /**
     * Gets the value of the faultCode property.
     * 
     * @return
     *     possible object is
     *     {@link FaultCodeType }
     *     
     */
    public FaultCodeType getFaultCode() {
        return faultCode;
    }

    /**
     * Sets the value of the faultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaultCodeType }
     *     
     */
    public void setFaultCode(FaultCodeType value) {
        this.faultCode = value;
    }

    /**
     * Gets the value of the faultSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaultSource() {
        return faultSource;
    }

    /**
     * Sets the value of the faultSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaultSource(String value) {
        this.faultSource = value;
    }

    /**
     * Gets the value of the multiIO property.
     * 
     * @return
     *     possible object is
     *     {@link MultiIOType }
     *     
     */
    public MultiIOType getMultiIO() {
        return multiIO;
    }

    /**
     * Sets the value of the multiIO property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiIOType }
     *     
     */
    public void setMultiIO(MultiIOType value) {
        this.multiIO = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link MessageType }
     *     
     */
    public MessageType getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageType }
     *     
     */
    public void setMessage(MessageType value) {
        this.message = value;
    }

    /**
     * Gets the value of the details property.
     * 
     * @return
     *     possible object is
     *     {@link DetailsType }
     *     
     */
    public DetailsType getDetails() {
        return details;
    }

    /**
     * Sets the value of the details property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetailsType }
     *     
     */
    public void setDetails(DetailsType value) {
        this.details = value;
    }

}
