//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.16 at 10:40:22 AM CEST 
//


package org.taktik.connector.business.medadminurses.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			     The NurseContractualCareDetailType element contains all the data
 * 			     needed to specify a Contractual Care.
 *             
 * 
 * <p>Java class for NurseContractualCareDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NurseContractualCareDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DecisionReference" type="{urn:be:cin:mycarenet:1.0:carenet:types}DecisionReferenceType" minOccurs="0"/>
 *         &lt;element name="ReferenceProviderModification" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ContractualType" type="{urn:be:cin:mycarenet:1.0:carenet:types}ContractualTypeType" minOccurs="0"/>
 *         &lt;element name="TreatmentPeriod" type="{urn:be:cin:mycarenet:1.0:carenet:types}PeriodLengthType"/>
 *         &lt;element name="CareDaysByWeek" type="{urn:be:cin:mycarenet:1.0:carenet:types}NbrOfDayInAWeekAllowZeroAllowEmpty" minOccurs="0"/>
 *         &lt;element name="VisitByDay" type="{urn:be:cin:mycarenet:1.0:carenet:types}VisitByDayTypeAllowEmpty" minOccurs="0"/>
 *         &lt;element name="Toilets" type="{urn:be:cin:mycarenet:1.0:carenet:types}ToiletsType" minOccurs="0"/>
 *         &lt;element name="Katz" type="{urn:be:cin:mycarenet:1.0:carenet:types}KatzType" minOccurs="0"/>
 *         &lt;element name="CarePlace" type="{urn:be:cin:mycarenet:1.0:carenet:types}CarePlaceType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NurseContractualCareDetailType", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", propOrder = {
    "decisionReference",
    "referenceProviderModification",
    "contractualType",
    "treatmentPeriod",
    "careDaysByWeek",
    "visitByDay",
    "toilets",
    "katz",
    "carePlace"
})
public class NurseContractualCareDetailType {

    @XmlElement(name = "DecisionReference", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    protected String decisionReference;
    @XmlElement(name = "ReferenceProviderModification", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", defaultValue = "false")
    protected Boolean referenceProviderModification;
    @XmlElement(name = "ContractualType", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    @XmlSchemaType(name = "string")
    protected ContractualTypeType contractualType;
    @XmlElement(name = "TreatmentPeriod", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected PeriodLengthType treatmentPeriod;
    @XmlElement(name = "CareDaysByWeek", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    protected String careDaysByWeek;
    @XmlElement(name = "VisitByDay", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    protected String visitByDay;
    @XmlElement(name = "Toilets", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    protected ToiletsType toilets;
    @XmlElement(name = "Katz", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    protected KatzType katz;
    @XmlElement(name = "CarePlace", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    protected CarePlaceType carePlace;

    /**
     * Gets the value of the decisionReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecisionReference() {
        return decisionReference;
    }

    /**
     * Sets the value of the decisionReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecisionReference(String value) {
        this.decisionReference = value;
    }

    /**
     * Gets the value of the referenceProviderModification property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReferenceProviderModification() {
        return referenceProviderModification;
    }

    /**
     * Sets the value of the referenceProviderModification property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReferenceProviderModification(Boolean value) {
        this.referenceProviderModification = value;
    }

    /**
     * Gets the value of the contractualType property.
     * 
     * @return
     *     possible object is
     *     {@link ContractualTypeType }
     *     
     */
    public ContractualTypeType getContractualType() {
        return contractualType;
    }

    /**
     * Sets the value of the contractualType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractualTypeType }
     *     
     */
    public void setContractualType(ContractualTypeType value) {
        this.contractualType = value;
    }

    /**
     * Gets the value of the treatmentPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodLengthType }
     *     
     */
    public PeriodLengthType getTreatmentPeriod() {
        return treatmentPeriod;
    }

    /**
     * Sets the value of the treatmentPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodLengthType }
     *     
     */
    public void setTreatmentPeriod(PeriodLengthType value) {
        this.treatmentPeriod = value;
    }

    /**
     * Gets the value of the careDaysByWeek property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCareDaysByWeek() {
        return careDaysByWeek;
    }

    /**
     * Sets the value of the careDaysByWeek property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCareDaysByWeek(String value) {
        this.careDaysByWeek = value;
    }

    /**
     * Gets the value of the visitByDay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisitByDay() {
        return visitByDay;
    }

    /**
     * Sets the value of the visitByDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisitByDay(String value) {
        this.visitByDay = value;
    }

    /**
     * Gets the value of the toilets property.
     * 
     * @return
     *     possible object is
     *     {@link ToiletsType }
     *     
     */
    public ToiletsType getToilets() {
        return toilets;
    }

    /**
     * Sets the value of the toilets property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToiletsType }
     *     
     */
    public void setToilets(ToiletsType value) {
        this.toilets = value;
    }

    /**
     * Gets the value of the katz property.
     * 
     * @return
     *     possible object is
     *     {@link KatzType }
     *     
     */
    public KatzType getKatz() {
        return katz;
    }

    /**
     * Sets the value of the katz property.
     * 
     * @param value
     *     allowed object is
     *     {@link KatzType }
     *     
     */
    public void setKatz(KatzType value) {
        this.katz = value;
    }

    /**
     * Gets the value of the carePlace property.
     * 
     * @return
     *     possible object is
     *     {@link CarePlaceType }
     *     
     */
    public CarePlaceType getCarePlace() {
        return carePlace;
    }

    /**
     * Sets the value of the carePlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarePlaceType }
     *     
     */
    public void setCarePlace(CarePlaceType value) {
        this.carePlace = value;
    }

}
