//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.16 at 10:40:22 AM CEST 
//


package org.taktik.connector.business.medadminurses.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NurseContractualCareRequestDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NurseContractualCareRequestDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NurseReference" type="{urn:be:cin:mycarenet:1.0:carenet:types}NurseReferenceType"/>
 *         &lt;element name="Requester" type="{urn:be:cin:mycarenet:1.0:carenet:types}NihiiType"/>
 *         &lt;element name="ContractualCareDetail" type="{urn:be:cin:mycarenet:1.0:carenet:types}NurseContractualCareDetailType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required" type="{urn:be:cin:mycarenet:1.0:carenet:types}RequestTypeType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NurseContractualCareRequestDetailType", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", propOrder = {
    "nurseReference",
    "requester",
    "contractualCareDetail"
})
public class NurseContractualCareRequestDetailType {

    @XmlElement(name = "NurseReference", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected String nurseReference;
    @XmlElement(name = "Requester", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected String requester;
    @XmlElement(name = "ContractualCareDetail", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected NurseContractualCareDetailType contractualCareDetail;
    @XmlAttribute(name = "type", required = true)
    protected RequestTypeType type;

    /**
     * Gets the value of the nurseReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNurseReference() {
        return nurseReference;
    }

    /**
     * Sets the value of the nurseReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNurseReference(String value) {
        this.nurseReference = value;
    }

    /**
     * Gets the value of the requester property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequester() {
        return requester;
    }

    /**
     * Sets the value of the requester property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequester(String value) {
        this.requester = value;
    }

    /**
     * Gets the value of the contractualCareDetail property.
     * 
     * @return
     *     possible object is
     *     {@link NurseContractualCareDetailType }
     *     
     */
    public NurseContractualCareDetailType getContractualCareDetail() {
        return contractualCareDetail;
    }

    /**
     * Sets the value of the contractualCareDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link NurseContractualCareDetailType }
     *     
     */
    public void setContractualCareDetail(NurseContractualCareDetailType value) {
        this.contractualCareDetail = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link RequestTypeType }
     *     
     */
    public RequestTypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestTypeType }
     *     
     */
    public void setType(RequestTypeType value) {
        this.type = value;
    }

}
