//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.16 at 10:40:22 AM CEST 
//


package org.taktik.connector.business.medadminurses.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for NurseContractualCareUpdateDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NurseContractualCareUpdateDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ConsultantDoctor" type="{urn:be:cin:mycarenet:1.0:carenet:types}NihiiType"/>
 *         &lt;element name="Provider" type="{urn:be:cin:mycarenet:1.0:carenet:types}NihiiType"/>
 *         &lt;element name="VisitDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="newValue" type="{urn:be:cin:mycarenet:1.0:carenet:types}NurseContractualCareDetailType"/>
 *         &lt;element name="PaliatifPatient" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required" type="{urn:be:cin:mycarenet:1.0:carenet:types}MessageNatureType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NurseContractualCareUpdateDetailType", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", propOrder = {
    "consultantDoctor",
    "provider",
    "visitDate",
    "newValue",
    "paliatifPatient"
})
public class NurseContractualCareUpdateDetailType {

    @XmlElement(name = "ConsultantDoctor", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected String consultantDoctor;
    @XmlElement(name = "Provider", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected String provider;
    @XmlElement(name = "VisitDate", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar visitDate;
    @XmlElement(namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected NurseContractualCareDetailType newValue;
    @XmlElement(name = "PaliatifPatient", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    protected Boolean paliatifPatient;
    @XmlAttribute(name = "type", required = true)
    protected MessageNatureType type;

    /**
     * Gets the value of the consultantDoctor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsultantDoctor() {
        return consultantDoctor;
    }

    /**
     * Sets the value of the consultantDoctor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsultantDoctor(String value) {
        this.consultantDoctor = value;
    }

    /**
     * Gets the value of the provider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvider() {
        return provider;
    }

    /**
     * Sets the value of the provider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvider(String value) {
        this.provider = value;
    }

    /**
     * Gets the value of the visitDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVisitDate() {
        return visitDate;
    }

    /**
     * Sets the value of the visitDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVisitDate(XMLGregorianCalendar value) {
        this.visitDate = value;
    }

    /**
     * Gets the value of the newValue property.
     * 
     * @return
     *     possible object is
     *     {@link NurseContractualCareDetailType }
     *     
     */
    public NurseContractualCareDetailType getNewValue() {
        return newValue;
    }

    /**
     * Sets the value of the newValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link NurseContractualCareDetailType }
     *     
     */
    public void setNewValue(NurseContractualCareDetailType value) {
        this.newValue = value;
    }

    /**
     * Gets the value of the paliatifPatient property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPaliatifPatient() {
        return paliatifPatient;
    }

    /**
     * Sets the value of the paliatifPatient property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPaliatifPatient(Boolean value) {
        this.paliatifPatient = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link MessageNatureType }
     *     
     */
    public MessageNatureType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageNatureType }
     *     
     */
    public void setType(MessageNatureType value) {
        this.type = value;
    }

}
