//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.16 at 10:40:22 AM CEST 
//


package org.taktik.connector.business.medadminurses.domain;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.taktik.connector.business.medadminurses.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SinglePalliativeCareRequest_QNAME = new QName("urn:be:cin:mycarenet:1.0:carenet:types", "SinglePalliativeCareRequest");
    private final static QName _PalliativeCareDetail_QNAME = new QName("urn:be:cin:mycarenet:1.0:carenet:types", "PalliativeCareDetail");
    private final static QName _PalliativeCareResponseDetail_QNAME = new QName("urn:be:cin:mycarenet:1.0:carenet:types", "PalliativeCareResponseDetail");
    private final static QName _MedAdminRequestList_QNAME = new QName("urn:be:cin:mycarenet:1.0:carenet:types", "MedAdminRequestList");
    private final static QName _SingleNurseContractualCareUpdate_QNAME = new QName("urn:be:cin:mycarenet:1.0:carenet:types", "SingleNurseContractualCareUpdate");
    private final static QName _SinglePalliativeCareResponse_QNAME = new QName("urn:be:cin:mycarenet:1.0:carenet:types", "SinglePalliativeCareResponse");
    private final static QName _MedAdminResponseList_QNAME = new QName("urn:be:cin:mycarenet:1.0:carenet:types", "MedAdminResponseList");
    private final static QName _SingleNurseContractualCareResponse_QNAME = new QName("urn:be:cin:mycarenet:1.0:carenet:types", "SingleNurseContractualCareResponse");
    private final static QName _SingleSpecificTechnicalCareRequest_QNAME = new QName("urn:be:cin:mycarenet:1.0:carenet:types", "SingleSpecificTechnicalCareRequest");
    private final static QName _SpecificTechnicalResponseCareDetail_QNAME = new QName("urn:be:cin:mycarenet:1.0:carenet:types", "SpecificTechnicalResponseCareDetail");
    private final static QName _NurseContractualCareUpdateDetail_QNAME = new QName("urn:be:cin:mycarenet:1.0:carenet:types", "NurseContractualCareUpdateDetail");
    private final static QName _NurseContractualCareRequestDetail_QNAME = new QName("urn:be:cin:mycarenet:1.0:carenet:types", "NurseContractualCareRequestDetail");
    private final static QName _SpecificTechnicalCareDetail_QNAME = new QName("urn:be:cin:mycarenet:1.0:carenet:types", "SpecificTechnicalCareDetail");
    private final static QName _SingleSpecificTechnicalCareResponse_QNAME = new QName("urn:be:cin:mycarenet:1.0:carenet:types", "SingleSpecificTechnicalCareResponse");
    private final static QName _SingleNurseContractualCareRequest_QNAME = new QName("urn:be:cin:mycarenet:1.0:carenet:types", "SingleNurseContractualCareRequest");
    private final static QName _NurseContractualCareResponseDetail_QNAME = new QName("urn:be:cin:mycarenet:1.0:carenet:types", "NurseContractualCareResponseDetail");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.taktik.connector.business.medadminurses.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PeriodLengthType }
     * 
     */
    public PeriodLengthType createPeriodLengthType() {
        return new PeriodLengthType();
    }

    /**
     * Create an instance of {@link SingleSpecificTechnicalCareResponseType }
     * 
     */
    public SingleSpecificTechnicalCareResponseType createSingleSpecificTechnicalCareResponseType() {
        return new SingleSpecificTechnicalCareResponseType();
    }

    /**
     * Create an instance of {@link SpecificTechnicalCareDetailType }
     * 
     */
    public SpecificTechnicalCareDetailType createSpecificTechnicalCareDetailType() {
        return new SpecificTechnicalCareDetailType();
    }

    /**
     * Create an instance of {@link NurseContractualCareResponseDetailType }
     * 
     */
    public NurseContractualCareResponseDetailType createNurseContractualCareResponseDetailType() {
        return new NurseContractualCareResponseDetailType();
    }

    /**
     * Create an instance of {@link SingleNurseContractualCareRequestType }
     * 
     */
    public SingleNurseContractualCareRequestType createSingleNurseContractualCareRequestType() {
        return new SingleNurseContractualCareRequestType();
    }

    /**
     * Create an instance of {@link SingleNurseContractualCareUpdateType }
     * 
     */
    public SingleNurseContractualCareUpdateType createSingleNurseContractualCareUpdateType() {
        return new SingleNurseContractualCareUpdateType();
    }

    /**
     * Create an instance of {@link MedAdminRequestListType }
     * 
     */
    public MedAdminRequestListType createMedAdminRequestListType() {
        return new MedAdminRequestListType();
    }

    /**
     * Create an instance of {@link PalliativeCareResponseDetailType }
     * 
     */
    public PalliativeCareResponseDetailType createPalliativeCareResponseDetailType() {
        return new PalliativeCareResponseDetailType();
    }

    /**
     * Create an instance of {@link PalliativeCareDetailType }
     * 
     */
    public PalliativeCareDetailType createPalliativeCareDetailType() {
        return new PalliativeCareDetailType();
    }

    /**
     * Create an instance of {@link SinglePalliativeCareRequestType }
     * 
     */
    public SinglePalliativeCareRequestType createSinglePalliativeCareRequestType() {
        return new SinglePalliativeCareRequestType();
    }

    /**
     * Create an instance of {@link NurseContractualCareRequestDetailType }
     * 
     */
    public NurseContractualCareRequestDetailType createNurseContractualCareRequestDetailType() {
        return new NurseContractualCareRequestDetailType();
    }

    /**
     * Create an instance of {@link NurseContractualCareUpdateDetailType }
     * 
     */
    public NurseContractualCareUpdateDetailType createNurseContractualCareUpdateDetailType() {
        return new NurseContractualCareUpdateDetailType();
    }

    /**
     * Create an instance of {@link SingleSpecificTechnicalCareRequestType }
     * 
     */
    public SingleSpecificTechnicalCareRequestType createSingleSpecificTechnicalCareRequestType() {
        return new SingleSpecificTechnicalCareRequestType();
    }

    /**
     * Create an instance of {@link SpecificTechnicalCareResponseDetailType }
     * 
     */
    public SpecificTechnicalCareResponseDetailType createSpecificTechnicalCareResponseDetailType() {
        return new SpecificTechnicalCareResponseDetailType();
    }

    /**
     * Create an instance of {@link MedAdminResponseListType }
     * 
     */
    public MedAdminResponseListType createMedAdminResponseListType() {
        return new MedAdminResponseListType();
    }

    /**
     * Create an instance of {@link SingleNurseContractualCareResponseType }
     * 
     */
    public SingleNurseContractualCareResponseType createSingleNurseContractualCareResponseType() {
        return new SingleNurseContractualCareResponseType();
    }

    /**
     * Create an instance of {@link SinglePalliativeCareResponseType }
     * 
     */
    public SinglePalliativeCareResponseType createSinglePalliativeCareResponseType() {
        return new SinglePalliativeCareResponseType();
    }

    /**
     * Create an instance of {@link CarePlaceType }
     * 
     */
    public CarePlaceType createCarePlaceType() {
        return new CarePlaceType();
    }

    /**
     * Create an instance of {@link PeriodType }
     * 
     */
    public PeriodType createPeriodType() {
        return new PeriodType();
    }

    /**
     * Create an instance of {@link MessageFaultType }
     * 
     */
    public MessageFaultType createMessageFaultType() {
        return new MessageFaultType();
    }

    /**
     * Create an instance of {@link MultiIOType }
     * 
     */
    public MultiIOType createMultiIOType() {
        return new MultiIOType();
    }

    /**
     * Create an instance of {@link MessageType }
     * 
     */
    public MessageType createMessageType() {
        return new MessageType();
    }

    /**
     * Create an instance of {@link CareReceiverIdType }
     * 
     */
    public CareReceiverIdType createCareReceiverIdType() {
        return new CareReceiverIdType();
    }

    /**
     * Create an instance of {@link PalliativeCareGroupType }
     * 
     */
    public PalliativeCareGroupType createPalliativeCareGroupType() {
        return new PalliativeCareGroupType();
    }

    /**
     * Create an instance of {@link ResponseDetailType }
     * 
     */
    public ResponseDetailType createResponseDetailType() {
        return new ResponseDetailType();
    }

    /**
     * Create an instance of {@link DetailsType }
     * 
     */
    public DetailsType createDetailsType() {
        return new DetailsType();
    }

    /**
     * Create an instance of {@link CareReceiverDetailType }
     * 
     */
    public CareReceiverDetailType createCareReceiverDetailType() {
        return new CareReceiverDetailType();
    }

    /**
     * Create an instance of {@link ExtCareReceiverDetailType }
     * 
     */
    public ExtCareReceiverDetailType createExtCareReceiverDetailType() {
        return new ExtCareReceiverDetailType();
    }

    /**
     * Create an instance of {@link DetailType }
     * 
     */
    public DetailType createDetailType() {
        return new DetailType();
    }

    /**
     * Create an instance of {@link PalliativeCareCareProviderType }
     * 
     */
    public PalliativeCareCareProviderType createPalliativeCareCareProviderType() {
        return new PalliativeCareCareProviderType();
    }

    /**
     * Create an instance of {@link DecisionType }
     * 
     */
    public DecisionType createDecisionType() {
        return new DecisionType();
    }

    /**
     * Create an instance of {@link KatzType }
     * 
     */
    public KatzType createKatzType() {
        return new KatzType();
    }

    /**
     * Create an instance of {@link ExtCareReceiverStrictIdType }
     * 
     */
    public ExtCareReceiverStrictIdType createExtCareReceiverStrictIdType() {
        return new ExtCareReceiverStrictIdType();
    }

    /**
     * Create an instance of {@link NurseContractualCareDetailType }
     * 
     */
    public NurseContractualCareDetailType createNurseContractualCareDetailType() {
        return new NurseContractualCareDetailType();
    }

    /**
     * Create an instance of {@link SpecificTechnicalCareTreatmentType }
     * 
     */
    public SpecificTechnicalCareTreatmentType createSpecificTechnicalCareTreatmentType() {
        return new SpecificTechnicalCareTreatmentType();
    }

    /**
     * Create an instance of {@link DementiaType }
     * 
     */
    public DementiaType createDementiaType() {
        return new DementiaType();
    }

    /**
     * Create an instance of {@link CareReceiverStrictIdType }
     * 
     */
    public CareReceiverStrictIdType createCareReceiverStrictIdType() {
        return new CareReceiverStrictIdType();
    }

    /**
     * Create an instance of {@link ToiletsType }
     * 
     */
    public ToiletsType createToiletsType() {
        return new ToiletsType();
    }

    /**
     * Create an instance of {@link PeriodLengthType.PeriodLength }
     * 
     */
    public PeriodLengthType.PeriodLength createPeriodLengthTypePeriodLength() {
        return new PeriodLengthType.PeriodLength();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SinglePalliativeCareRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:cin:mycarenet:1.0:carenet:types", name = "SinglePalliativeCareRequest")
    public JAXBElement<SinglePalliativeCareRequestType> createSinglePalliativeCareRequest(SinglePalliativeCareRequestType value) {
        return new JAXBElement<SinglePalliativeCareRequestType>(_SinglePalliativeCareRequest_QNAME, SinglePalliativeCareRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PalliativeCareDetailType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:cin:mycarenet:1.0:carenet:types", name = "PalliativeCareDetail")
    public JAXBElement<PalliativeCareDetailType> createPalliativeCareDetail(PalliativeCareDetailType value) {
        return new JAXBElement<PalliativeCareDetailType>(_PalliativeCareDetail_QNAME, PalliativeCareDetailType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PalliativeCareResponseDetailType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:cin:mycarenet:1.0:carenet:types", name = "PalliativeCareResponseDetail")
    public JAXBElement<PalliativeCareResponseDetailType> createPalliativeCareResponseDetail(PalliativeCareResponseDetailType value) {
        return new JAXBElement<PalliativeCareResponseDetailType>(_PalliativeCareResponseDetail_QNAME, PalliativeCareResponseDetailType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MedAdminRequestListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:cin:mycarenet:1.0:carenet:types", name = "MedAdminRequestList")
    public JAXBElement<MedAdminRequestListType> createMedAdminRequestList(MedAdminRequestListType value) {
        return new JAXBElement<MedAdminRequestListType>(_MedAdminRequestList_QNAME, MedAdminRequestListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleNurseContractualCareUpdateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:cin:mycarenet:1.0:carenet:types", name = "SingleNurseContractualCareUpdate")
    public JAXBElement<SingleNurseContractualCareUpdateType> createSingleNurseContractualCareUpdate(SingleNurseContractualCareUpdateType value) {
        return new JAXBElement<SingleNurseContractualCareUpdateType>(_SingleNurseContractualCareUpdate_QNAME, SingleNurseContractualCareUpdateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SinglePalliativeCareResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:cin:mycarenet:1.0:carenet:types", name = "SinglePalliativeCareResponse")
    public JAXBElement<SinglePalliativeCareResponseType> createSinglePalliativeCareResponse(SinglePalliativeCareResponseType value) {
        return new JAXBElement<SinglePalliativeCareResponseType>(_SinglePalliativeCareResponse_QNAME, SinglePalliativeCareResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MedAdminResponseListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:cin:mycarenet:1.0:carenet:types", name = "MedAdminResponseList")
    public JAXBElement<MedAdminResponseListType> createMedAdminResponseList(MedAdminResponseListType value) {
        return new JAXBElement<MedAdminResponseListType>(_MedAdminResponseList_QNAME, MedAdminResponseListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleNurseContractualCareResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:cin:mycarenet:1.0:carenet:types", name = "SingleNurseContractualCareResponse")
    public JAXBElement<SingleNurseContractualCareResponseType> createSingleNurseContractualCareResponse(SingleNurseContractualCareResponseType value) {
        return new JAXBElement<SingleNurseContractualCareResponseType>(_SingleNurseContractualCareResponse_QNAME, SingleNurseContractualCareResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleSpecificTechnicalCareRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:cin:mycarenet:1.0:carenet:types", name = "SingleSpecificTechnicalCareRequest")
    public JAXBElement<SingleSpecificTechnicalCareRequestType> createSingleSpecificTechnicalCareRequest(SingleSpecificTechnicalCareRequestType value) {
        return new JAXBElement<SingleSpecificTechnicalCareRequestType>(_SingleSpecificTechnicalCareRequest_QNAME, SingleSpecificTechnicalCareRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpecificTechnicalCareResponseDetailType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:cin:mycarenet:1.0:carenet:types", name = "SpecificTechnicalResponseCareDetail")
    public JAXBElement<SpecificTechnicalCareResponseDetailType> createSpecificTechnicalResponseCareDetail(SpecificTechnicalCareResponseDetailType value) {
        return new JAXBElement<SpecificTechnicalCareResponseDetailType>(_SpecificTechnicalResponseCareDetail_QNAME, SpecificTechnicalCareResponseDetailType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NurseContractualCareUpdateDetailType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:cin:mycarenet:1.0:carenet:types", name = "NurseContractualCareUpdateDetail")
    public JAXBElement<NurseContractualCareUpdateDetailType> createNurseContractualCareUpdateDetail(NurseContractualCareUpdateDetailType value) {
        return new JAXBElement<NurseContractualCareUpdateDetailType>(_NurseContractualCareUpdateDetail_QNAME, NurseContractualCareUpdateDetailType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NurseContractualCareRequestDetailType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:cin:mycarenet:1.0:carenet:types", name = "NurseContractualCareRequestDetail")
    public JAXBElement<NurseContractualCareRequestDetailType> createNurseContractualCareRequestDetail(NurseContractualCareRequestDetailType value) {
        return new JAXBElement<NurseContractualCareRequestDetailType>(_NurseContractualCareRequestDetail_QNAME, NurseContractualCareRequestDetailType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpecificTechnicalCareDetailType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:cin:mycarenet:1.0:carenet:types", name = "SpecificTechnicalCareDetail")
    public JAXBElement<SpecificTechnicalCareDetailType> createSpecificTechnicalCareDetail(SpecificTechnicalCareDetailType value) {
        return new JAXBElement<SpecificTechnicalCareDetailType>(_SpecificTechnicalCareDetail_QNAME, SpecificTechnicalCareDetailType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleSpecificTechnicalCareResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:cin:mycarenet:1.0:carenet:types", name = "SingleSpecificTechnicalCareResponse")
    public JAXBElement<SingleSpecificTechnicalCareResponseType> createSingleSpecificTechnicalCareResponse(SingleSpecificTechnicalCareResponseType value) {
        return new JAXBElement<SingleSpecificTechnicalCareResponseType>(_SingleSpecificTechnicalCareResponse_QNAME, SingleSpecificTechnicalCareResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleNurseContractualCareRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:cin:mycarenet:1.0:carenet:types", name = "SingleNurseContractualCareRequest")
    public JAXBElement<SingleNurseContractualCareRequestType> createSingleNurseContractualCareRequest(SingleNurseContractualCareRequestType value) {
        return new JAXBElement<SingleNurseContractualCareRequestType>(_SingleNurseContractualCareRequest_QNAME, SingleNurseContractualCareRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NurseContractualCareResponseDetailType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:cin:mycarenet:1.0:carenet:types", name = "NurseContractualCareResponseDetail")
    public JAXBElement<NurseContractualCareResponseDetailType> createNurseContractualCareResponseDetail(NurseContractualCareResponseDetailType value) {
        return new JAXBElement<NurseContractualCareResponseDetailType>(_NurseContractualCareResponseDetail_QNAME, NurseContractualCareResponseDetailType.class, null, value);
    }

}
