//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.16 at 10:40:22 AM CEST 
//


package org.taktik.connector.business.medadminurses.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PalliativeCareCareProviderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PalliativeCareCareProviderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Nurse" type="{urn:be:cin:mycarenet:1.0:carenet:types}NihiiType" minOccurs="0"/>
 *         &lt;element name="MultidisciplinaryTeam" type="{urn:be:cin:mycarenet:1.0:carenet:types}NihiiType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PalliativeCareCareProviderType", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", propOrder = {
    "nurse",
    "multidisciplinaryTeam"
})
public class PalliativeCareCareProviderType {

    @XmlElement(name = "Nurse", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    protected String nurse;
    @XmlElement(name = "MultidisciplinaryTeam", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    protected String multidisciplinaryTeam;

    /**
     * Gets the value of the nurse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNurse() {
        return nurse;
    }

    /**
     * Sets the value of the nurse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNurse(String value) {
        this.nurse = value;
    }

    /**
     * Gets the value of the multidisciplinaryTeam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultidisciplinaryTeam() {
        return multidisciplinaryTeam;
    }

    /**
     * Sets the value of the multidisciplinaryTeam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultidisciplinaryTeam(String value) {
        this.multidisciplinaryTeam = value;
    }

}
