//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.16 at 10:40:22 AM CEST 
//


package org.taktik.connector.business.medadminurses.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PalliativeCareDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PalliativeCareDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NurseReference" type="{urn:be:cin:mycarenet:1.0:carenet:types}NurseReferenceType"/>
 *         &lt;element name="Requester" type="{urn:be:cin:mycarenet:1.0:carenet:types}NihiiType"/>
 *         &lt;element name="PeriodStart" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Group" type="{urn:be:cin:mycarenet:1.0:carenet:types}PalliativeCareGroupType"/>
 *         &lt;element name="UsualDoctor" type="{urn:be:cin:mycarenet:1.0:carenet:types}NihiiType"/>
 *         &lt;element name="CareProvider" type="{urn:be:cin:mycarenet:1.0:carenet:types}PalliativeCareCareProviderType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PalliativeCareDetailType", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", propOrder = {
    "nurseReference",
    "requester",
    "periodStart",
    "group",
    "usualDoctor",
    "careProvider"
})
public class PalliativeCareDetailType {

    @XmlElement(name = "NurseReference", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected String nurseReference;
    @XmlElement(name = "Requester", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected String requester;
    @XmlElement(name = "PeriodStart", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar periodStart;
    @XmlElement(name = "Group", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected PalliativeCareGroupType group;
    @XmlElement(name = "UsualDoctor", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected String usualDoctor;
    @XmlElement(name = "CareProvider", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected PalliativeCareCareProviderType careProvider;

    /**
     * Gets the value of the nurseReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNurseReference() {
        return nurseReference;
    }

    /**
     * Sets the value of the nurseReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNurseReference(String value) {
        this.nurseReference = value;
    }

    /**
     * Gets the value of the requester property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequester() {
        return requester;
    }

    /**
     * Sets the value of the requester property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequester(String value) {
        this.requester = value;
    }

    /**
     * Gets the value of the periodStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPeriodStart() {
        return periodStart;
    }

    /**
     * Sets the value of the periodStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPeriodStart(XMLGregorianCalendar value) {
        this.periodStart = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link PalliativeCareGroupType }
     *     
     */
    public PalliativeCareGroupType getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link PalliativeCareGroupType }
     *     
     */
    public void setGroup(PalliativeCareGroupType value) {
        this.group = value;
    }

    /**
     * Gets the value of the usualDoctor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsualDoctor() {
        return usualDoctor;
    }

    /**
     * Sets the value of the usualDoctor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsualDoctor(String value) {
        this.usualDoctor = value;
    }

    /**
     * Gets the value of the careProvider property.
     * 
     * @return
     *     possible object is
     *     {@link PalliativeCareCareProviderType }
     *     
     */
    public PalliativeCareCareProviderType getCareProvider() {
        return careProvider;
    }

    /**
     * Sets the value of the careProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link PalliativeCareCareProviderType }
     *     
     */
    public void setCareProvider(PalliativeCareCareProviderType value) {
        this.careProvider = value;
    }

}
