//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.16 at 10:40:22 AM CEST 
//


package org.taktik.connector.business.medadminurses.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PeriodLengthType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PeriodLengthType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PeriodStart" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="PeriodEnd" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *           &lt;element name="PeriodLength">
 *             &lt;complexType>
 *               &lt;simpleContent>
 *                 &lt;extension base="&lt;urn:be:cin:mycarenet:1.0:carenet:types>NumericalType_2">
 *                   &lt;attribute name="type" use="required" type="{urn:be:cin:mycarenet:1.0:carenet:types}PeriodLengthTypeType" />
 *                 &lt;/extension>
 *               &lt;/simpleContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PeriodLengthType", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", propOrder = {
    "periodStart",
    "periodEnd",
    "periodLength"
})
public class PeriodLengthType {

    @XmlElement(name = "PeriodStart", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar periodStart;
    @XmlElement(name = "PeriodEnd", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar periodEnd;
    @XmlElement(name = "PeriodLength", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    protected PeriodLengthType.PeriodLength periodLength;

    /**
     * Gets the value of the periodStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPeriodStart() {
        return periodStart;
    }

    /**
     * Sets the value of the periodStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPeriodStart(XMLGregorianCalendar value) {
        this.periodStart = value;
    }

    /**
     * Gets the value of the periodEnd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPeriodEnd() {
        return periodEnd;
    }

    /**
     * Sets the value of the periodEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPeriodEnd(XMLGregorianCalendar value) {
        this.periodEnd = value;
    }

    /**
     * Gets the value of the periodLength property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodLengthType.PeriodLength }
     *     
     */
    public PeriodLengthType.PeriodLength getPeriodLength() {
        return periodLength;
    }

    /**
     * Sets the value of the periodLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodLengthType.PeriodLength }
     *     
     */
    public void setPeriodLength(PeriodLengthType.PeriodLength value) {
        this.periodLength = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;urn:be:cin:mycarenet:1.0:carenet:types>NumericalType_2">
     *       &lt;attribute name="type" use="required" type="{urn:be:cin:mycarenet:1.0:carenet:types}PeriodLengthTypeType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class PeriodLength {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "type", required = true)
        protected PeriodLengthTypeType type;

        /**
         * 
         * 			   NumericalType Limited to a length of 2
         *             
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link PeriodLengthTypeType }
         *     
         */
        public PeriodLengthTypeType getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link PeriodLengthTypeType }
         *     
         */
        public void setType(PeriodLengthTypeType value) {
            this.type = value;
        }

    }

}
