//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.16 at 10:40:22 AM CEST 
//


package org.taktik.connector.business.medadminurses.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResponseDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResponseDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ConsultantDoctor" type="{urn:be:cin:mycarenet:1.0:carenet:types}NihiiType"/>
 *         &lt;element name="Decision" type="{urn:be:cin:mycarenet:1.0:carenet:types}DecisionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponseDetailType", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", propOrder = {
    "consultantDoctor",
    "decision"
})
public class ResponseDetailType {

    @XmlElement(name = "ConsultantDoctor", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected String consultantDoctor;
    @XmlElement(name = "Decision", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected DecisionType decision;

    /**
     * Gets the value of the consultantDoctor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsultantDoctor() {
        return consultantDoctor;
    }

    /**
     * Sets the value of the consultantDoctor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsultantDoctor(String value) {
        this.consultantDoctor = value;
    }

    /**
     * Gets the value of the decision property.
     * 
     * @return
     *     possible object is
     *     {@link DecisionType }
     *     
     */
    public DecisionType getDecision() {
        return decision;
    }

    /**
     * Sets the value of the decision property.
     * 
     * @param value
     *     allowed object is
     *     {@link DecisionType }
     *     
     */
    public void setDecision(DecisionType value) {
        this.decision = value;
    }

}
