//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.16 at 10:40:22 AM CEST 
//


package org.taktik.connector.business.medadminurses.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SingleNurseContractualCareUpdateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SingleNurseContractualCareUpdateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CareReceiverDetail" type="{urn:be:cin:mycarenet:1.0:carenet:types}ExtCareReceiverDetailType"/>
 *         &lt;element ref="{urn:be:cin:mycarenet:1.0:carenet:types}NurseContractualCareUpdateDetail"/>
 *         &lt;element name="NurseContractualCarePreviousDetail" type="{urn:be:cin:mycarenet:1.0:carenet:types}NurseContractualCareDetailType"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:be:cin:mycarenet:1.0:carenet:types}MessageHeader"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SingleNurseContractualCareUpdateType", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", propOrder = {
    "careReceiverDetail",
    "nurseContractualCareUpdateDetail",
    "nurseContractualCarePreviousDetail"
})
public class SingleNurseContractualCareUpdateType {

    @XmlElement(name = "CareReceiverDetail", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected ExtCareReceiverDetailType careReceiverDetail;
    @XmlElement(name = "NurseContractualCareUpdateDetail", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected NurseContractualCareUpdateDetailType nurseContractualCareUpdateDetail;
    @XmlElement(name = "NurseContractualCarePreviousDetail", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected NurseContractualCareDetailType nurseContractualCarePreviousDetail;
    @XmlAttribute(name = "MessageName", required = true)
    protected MessageNameType messageName;
    @XmlAttribute(name = "Version", required = true)
    protected String version;
    @XmlAttribute(name = "Duplicate", required = true)
    protected boolean duplicate;
    @XmlAttribute(name = "TestFlag", required = true)
    protected boolean testFlag;
    @XmlAttribute(name = "SenderReference", required = true)
    protected String senderReference;
    @XmlAttribute(name = "ReceiverReference")
    protected String receiverReference;
    @XmlAttribute(name = "Synchronous", required = true)
    protected boolean synchronous;

    /**
     * Gets the value of the careReceiverDetail property.
     * 
     * @return
     *     possible object is
     *     {@link ExtCareReceiverDetailType }
     *     
     */
    public ExtCareReceiverDetailType getCareReceiverDetail() {
        return careReceiverDetail;
    }

    /**
     * Sets the value of the careReceiverDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtCareReceiverDetailType }
     *     
     */
    public void setCareReceiverDetail(ExtCareReceiverDetailType value) {
        this.careReceiverDetail = value;
    }

    /**
     * Gets the value of the nurseContractualCareUpdateDetail property.
     * 
     * @return
     *     possible object is
     *     {@link NurseContractualCareUpdateDetailType }
     *     
     */
    public NurseContractualCareUpdateDetailType getNurseContractualCareUpdateDetail() {
        return nurseContractualCareUpdateDetail;
    }

    /**
     * Sets the value of the nurseContractualCareUpdateDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link NurseContractualCareUpdateDetailType }
     *     
     */
    public void setNurseContractualCareUpdateDetail(NurseContractualCareUpdateDetailType value) {
        this.nurseContractualCareUpdateDetail = value;
    }

    /**
     * Gets the value of the nurseContractualCarePreviousDetail property.
     * 
     * @return
     *     possible object is
     *     {@link NurseContractualCareDetailType }
     *     
     */
    public NurseContractualCareDetailType getNurseContractualCarePreviousDetail() {
        return nurseContractualCarePreviousDetail;
    }

    /**
     * Sets the value of the nurseContractualCarePreviousDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link NurseContractualCareDetailType }
     *     
     */
    public void setNurseContractualCarePreviousDetail(NurseContractualCareDetailType value) {
        this.nurseContractualCarePreviousDetail = value;
    }

    /**
     * Gets the value of the messageName property.
     * 
     * @return
     *     possible object is
     *     {@link MessageNameType }
     *     
     */
    public MessageNameType getMessageName() {
        return messageName;
    }

    /**
     * Sets the value of the messageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageNameType }
     *     
     */
    public void setMessageName(MessageNameType value) {
        this.messageName = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the duplicate property.
     * 
     */
    public boolean isDuplicate() {
        return duplicate;
    }

    /**
     * Sets the value of the duplicate property.
     * 
     */
    public void setDuplicate(boolean value) {
        this.duplicate = value;
    }

    /**
     * Gets the value of the testFlag property.
     * 
     */
    public boolean isTestFlag() {
        return testFlag;
    }

    /**
     * Sets the value of the testFlag property.
     * 
     */
    public void setTestFlag(boolean value) {
        this.testFlag = value;
    }

    /**
     * Gets the value of the senderReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderReference() {
        return senderReference;
    }

    /**
     * Sets the value of the senderReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderReference(String value) {
        this.senderReference = value;
    }

    /**
     * Gets the value of the receiverReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverReference() {
        return receiverReference;
    }

    /**
     * Sets the value of the receiverReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverReference(String value) {
        this.receiverReference = value;
    }

    /**
     * Gets the value of the synchronous property.
     * 
     */
    public boolean isSynchronous() {
        return synchronous;
    }

    /**
     * Sets the value of the synchronous property.
     * 
     */
    public void setSynchronous(boolean value) {
        this.synchronous = value;
    }

}
