//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.16 at 10:40:22 AM CEST 
//


package org.taktik.connector.business.medadminurses.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SingleSpecificTechnicalCareResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SingleSpecificTechnicalCareResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="CareReceiverId" type="{urn:be:cin:mycarenet:1.0:carenet:types}ExtCareReceiverStrictIdType"/>
 *             &lt;element ref="{urn:be:cin:mycarenet:1.0:carenet:types}SpecificTechnicalCareDetail"/>
 *             &lt;element name="MessageFault" type="{urn:be:cin:mycarenet:1.0:carenet:types}MessageFaultType"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="CareReceiverDetail" type="{urn:be:cin:mycarenet:1.0:carenet:types}ExtCareReceiverDetailType"/>
 *             &lt;element ref="{urn:be:cin:mycarenet:1.0:carenet:types}SpecificTechnicalResponseCareDetail"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:be:cin:mycarenet:1.0:carenet:types}MessageHeader"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SingleSpecificTechnicalCareResponseType", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", propOrder = {
    "careReceiverId",
    "specificTechnicalCareDetail",
    "messageFault",
    "careReceiverDetail",
    "specificTechnicalResponseCareDetail"
})
public class SingleSpecificTechnicalCareResponseType {

    @XmlElement(name = "CareReceiverId", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    protected ExtCareReceiverStrictIdType careReceiverId;
    @XmlElement(name = "SpecificTechnicalCareDetail", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    protected SpecificTechnicalCareDetailType specificTechnicalCareDetail;
    @XmlElement(name = "MessageFault", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    protected MessageFaultType messageFault;
    @XmlElement(name = "CareReceiverDetail", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    protected ExtCareReceiverDetailType careReceiverDetail;
    @XmlElement(name = "SpecificTechnicalResponseCareDetail", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    protected SpecificTechnicalCareResponseDetailType specificTechnicalResponseCareDetail;
    @XmlAttribute(name = "MessageName", required = true)
    protected MessageNameType messageName;
    @XmlAttribute(name = "Version", required = true)
    protected String version;
    @XmlAttribute(name = "Duplicate", required = true)
    protected boolean duplicate;
    @XmlAttribute(name = "TestFlag", required = true)
    protected boolean testFlag;
    @XmlAttribute(name = "SenderReference", required = true)
    protected String senderReference;
    @XmlAttribute(name = "ReceiverReference")
    protected String receiverReference;
    @XmlAttribute(name = "Synchronous", required = true)
    protected boolean synchronous;

    /**
     * Gets the value of the careReceiverId property.
     * 
     * @return
     *     possible object is
     *     {@link ExtCareReceiverStrictIdType }
     *     
     */
    public ExtCareReceiverStrictIdType getCareReceiverId() {
        return careReceiverId;
    }

    /**
     * Sets the value of the careReceiverId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtCareReceiverStrictIdType }
     *     
     */
    public void setCareReceiverId(ExtCareReceiverStrictIdType value) {
        this.careReceiverId = value;
    }

    /**
     * Gets the value of the specificTechnicalCareDetail property.
     * 
     * @return
     *     possible object is
     *     {@link SpecificTechnicalCareDetailType }
     *     
     */
    public SpecificTechnicalCareDetailType getSpecificTechnicalCareDetail() {
        return specificTechnicalCareDetail;
    }

    /**
     * Sets the value of the specificTechnicalCareDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecificTechnicalCareDetailType }
     *     
     */
    public void setSpecificTechnicalCareDetail(SpecificTechnicalCareDetailType value) {
        this.specificTechnicalCareDetail = value;
    }

    /**
     * Gets the value of the messageFault property.
     * 
     * @return
     *     possible object is
     *     {@link MessageFaultType }
     *     
     */
    public MessageFaultType getMessageFault() {
        return messageFault;
    }

    /**
     * Sets the value of the messageFault property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageFaultType }
     *     
     */
    public void setMessageFault(MessageFaultType value) {
        this.messageFault = value;
    }

    /**
     * Gets the value of the careReceiverDetail property.
     * 
     * @return
     *     possible object is
     *     {@link ExtCareReceiverDetailType }
     *     
     */
    public ExtCareReceiverDetailType getCareReceiverDetail() {
        return careReceiverDetail;
    }

    /**
     * Sets the value of the careReceiverDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtCareReceiverDetailType }
     *     
     */
    public void setCareReceiverDetail(ExtCareReceiverDetailType value) {
        this.careReceiverDetail = value;
    }

    /**
     * Gets the value of the specificTechnicalResponseCareDetail property.
     * 
     * @return
     *     possible object is
     *     {@link SpecificTechnicalCareResponseDetailType }
     *     
     */
    public SpecificTechnicalCareResponseDetailType getSpecificTechnicalResponseCareDetail() {
        return specificTechnicalResponseCareDetail;
    }

    /**
     * Sets the value of the specificTechnicalResponseCareDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecificTechnicalCareResponseDetailType }
     *     
     */
    public void setSpecificTechnicalResponseCareDetail(SpecificTechnicalCareResponseDetailType value) {
        this.specificTechnicalResponseCareDetail = value;
    }

    /**
     * Gets the value of the messageName property.
     * 
     * @return
     *     possible object is
     *     {@link MessageNameType }
     *     
     */
    public MessageNameType getMessageName() {
        return messageName;
    }

    /**
     * Sets the value of the messageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageNameType }
     *     
     */
    public void setMessageName(MessageNameType value) {
        this.messageName = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the duplicate property.
     * 
     */
    public boolean isDuplicate() {
        return duplicate;
    }

    /**
     * Sets the value of the duplicate property.
     * 
     */
    public void setDuplicate(boolean value) {
        this.duplicate = value;
    }

    /**
     * Gets the value of the testFlag property.
     * 
     */
    public boolean isTestFlag() {
        return testFlag;
    }

    /**
     * Sets the value of the testFlag property.
     * 
     */
    public void setTestFlag(boolean value) {
        this.testFlag = value;
    }

    /**
     * Gets the value of the senderReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderReference() {
        return senderReference;
    }

    /**
     * Sets the value of the senderReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderReference(String value) {
        this.senderReference = value;
    }

    /**
     * Gets the value of the receiverReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverReference() {
        return receiverReference;
    }

    /**
     * Sets the value of the receiverReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverReference(String value) {
        this.receiverReference = value;
    }

    /**
     * Gets the value of the synchronous property.
     * 
     */
    public boolean isSynchronous() {
        return synchronous;
    }

    /**
     * Sets the value of the synchronous property.
     * 
     */
    public void setSynchronous(boolean value) {
        this.synchronous = value;
    }

}
