//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.16 at 10:40:22 AM CEST 
//


package org.taktik.connector.business.medadminurses.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SinglePalliativeCareRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SinglePalliativeCareRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CareReceiverId" type="{urn:be:cin:mycarenet:1.0:carenet:types}ExtCareReceiverStrictIdType"/>
 *         &lt;element ref="{urn:be:cin:mycarenet:1.0:carenet:types}PalliativeCareDetail"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:be:cin:mycarenet:1.0:carenet:types}MessageHeader"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SinglePalliativeCareRequestType", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", propOrder = {
    "careReceiverId",
    "palliativeCareDetail"
})
public class SinglePalliativeCareRequestType {

    @XmlElement(name = "CareReceiverId", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected ExtCareReceiverStrictIdType careReceiverId;
    @XmlElement(name = "PalliativeCareDetail", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected PalliativeCareDetailType palliativeCareDetail;
    @XmlAttribute(name = "MessageName", required = true)
    protected MessageNameType messageName;
    @XmlAttribute(name = "Version", required = true)
    protected String version;
    @XmlAttribute(name = "Duplicate", required = true)
    protected boolean duplicate;
    @XmlAttribute(name = "TestFlag", required = true)
    protected boolean testFlag;
    @XmlAttribute(name = "SenderReference", required = true)
    protected String senderReference;
    @XmlAttribute(name = "ReceiverReference")
    protected String receiverReference;
    @XmlAttribute(name = "Synchronous", required = true)
    protected boolean synchronous;

    /**
     * Gets the value of the careReceiverId property.
     * 
     * @return
     *     possible object is
     *     {@link ExtCareReceiverStrictIdType }
     *     
     */
    public ExtCareReceiverStrictIdType getCareReceiverId() {
        return careReceiverId;
    }

    /**
     * Sets the value of the careReceiverId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtCareReceiverStrictIdType }
     *     
     */
    public void setCareReceiverId(ExtCareReceiverStrictIdType value) {
        this.careReceiverId = value;
    }

    /**
     * Gets the value of the palliativeCareDetail property.
     * 
     * @return
     *     possible object is
     *     {@link PalliativeCareDetailType }
     *     
     */
    public PalliativeCareDetailType getPalliativeCareDetail() {
        return palliativeCareDetail;
    }

    /**
     * Sets the value of the palliativeCareDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link PalliativeCareDetailType }
     *     
     */
    public void setPalliativeCareDetail(PalliativeCareDetailType value) {
        this.palliativeCareDetail = value;
    }

    /**
     * Gets the value of the messageName property.
     * 
     * @return
     *     possible object is
     *     {@link MessageNameType }
     *     
     */
    public MessageNameType getMessageName() {
        return messageName;
    }

    /**
     * Sets the value of the messageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageNameType }
     *     
     */
    public void setMessageName(MessageNameType value) {
        this.messageName = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the duplicate property.
     * 
     */
    public boolean isDuplicate() {
        return duplicate;
    }

    /**
     * Sets the value of the duplicate property.
     * 
     */
    public void setDuplicate(boolean value) {
        this.duplicate = value;
    }

    /**
     * Gets the value of the testFlag property.
     * 
     */
    public boolean isTestFlag() {
        return testFlag;
    }

    /**
     * Sets the value of the testFlag property.
     * 
     */
    public void setTestFlag(boolean value) {
        this.testFlag = value;
    }

    /**
     * Gets the value of the senderReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderReference() {
        return senderReference;
    }

    /**
     * Sets the value of the senderReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderReference(String value) {
        this.senderReference = value;
    }

    /**
     * Gets the value of the receiverReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverReference() {
        return receiverReference;
    }

    /**
     * Sets the value of the receiverReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverReference(String value) {
        this.receiverReference = value;
    }

    /**
     * Gets the value of the synchronous property.
     * 
     */
    public boolean isSynchronous() {
        return synchronous;
    }

    /**
     * Sets the value of the synchronous property.
     * 
     */
    public void setSynchronous(boolean value) {
        this.synchronous = value;
    }

}
