//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.16 at 10:40:22 AM CEST 
//


package org.taktik.connector.business.medadminurses.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpecificTechnicalCareTreatmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpecificTechnicalCareTreatmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Reason" type="{urn:be:cin:mycarenet:1.0:carenet:types}String_150" minOccurs="0"/>
 *         &lt;element name="Frequency" type="{urn:be:cin:mycarenet:1.0:carenet:types}String_50" minOccurs="0"/>
 *         &lt;element name="Product" type="{urn:be:cin:mycarenet:1.0:carenet:types}String_150" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required" type="{urn:be:cin:mycarenet:1.0:carenet:types}SpecificTechnicalCareTypeType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpecificTechnicalCareTreatmentType", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", propOrder = {
    "reason",
    "frequency",
    "product"
})
public class SpecificTechnicalCareTreatmentType {

    @XmlElement(name = "Reason", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    protected String reason;
    @XmlElement(name = "Frequency", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    protected String frequency;
    @XmlElement(name = "Product", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
    protected String product;
    @XmlAttribute(name = "type", required = true)
    protected SpecificTechnicalCareTypeType type;

    /**
     * Gets the value of the reason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReason(String value) {
        this.reason = value;
    }

    /**
     * Gets the value of the frequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrequency() {
        return frequency;
    }

    /**
     * Sets the value of the frequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrequency(String value) {
        this.frequency = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProduct(String value) {
        this.product = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link SpecificTechnicalCareTypeType }
     *     
     */
    public SpecificTechnicalCareTypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecificTechnicalCareTypeType }
     *     
     */
    public void setType(SpecificTechnicalCareTypeType value) {
        this.type = value;
    }

}
