//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.16 at 10:40:22 AM CEST 
//


package org.taktik.connector.business.medadminurses.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpecificTechnicalCareResponseDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpecificTechnicalCareResponseDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NurseReference" type="{urn:be:cin:mycarenet:1.0:carenet:types}NurseReferenceType"/>
 *         &lt;element name="MessageName" type="{urn:be:cin:mycarenet:1.0:carenet:types}MessageNameType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpecificTechnicalCareResponseDetailType", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", propOrder = {
    "nurseReference",
    "messageName"
})
public class SpecificTechnicalCareResponseDetailType {

    @XmlElement(name = "NurseReference", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected String nurseReference;
    @XmlElement(name = "MessageName", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    @XmlSchemaType(name = "string")
    protected MessageNameType messageName;

    /**
     * Gets the value of the nurseReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNurseReference() {
        return nurseReference;
    }

    /**
     * Sets the value of the nurseReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNurseReference(String value) {
        this.nurseReference = value;
    }

    /**
     * Gets the value of the messageName property.
     * 
     * @return
     *     possible object is
     *     {@link MessageNameType }
     *     
     */
    public MessageNameType getMessageName() {
        return messageName;
    }

    /**
     * Sets the value of the messageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageNameType }
     *     
     */
    public void setMessageName(MessageNameType value) {
        this.messageName = value;
    }

}
