//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.16 at 10:40:22 AM CEST 
//


package org.taktik.connector.business.medadminurses.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpecificTechnicalCareDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpecificTechnicalCareDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NurseReference" type="{urn:be:cin:mycarenet:1.0:carenet:types}NurseReferenceType"/>
 *         &lt;element name="Requester" type="{urn:be:cin:mycarenet:1.0:carenet:types}NihiiType"/>
 *         &lt;element name="TreatmentPeriod" type="{urn:be:cin:mycarenet:1.0:carenet:types}PeriodType"/>
 *         &lt;element name="Prescriber" type="{urn:be:cin:mycarenet:1.0:carenet:types}NihiiType"/>
 *         &lt;element name="AdministeredProduct" type="{urn:be:cin:mycarenet:1.0:carenet:types}FillerType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required" type="{urn:be:cin:mycarenet:1.0:carenet:types}SpecificTechnicalCareTypeType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpecificTechnicalCareDetailType", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", propOrder = {
    "nurseReference",
    "requester",
    "treatmentPeriod",
    "prescriber",
    "administeredProduct"
})
public class SpecificTechnicalCareDetailType {

    @XmlElement(name = "NurseReference", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected String nurseReference;
    @XmlElement(name = "Requester", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected String requester;
    @XmlElement(name = "TreatmentPeriod", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected PeriodType treatmentPeriod;
    @XmlElement(name = "Prescriber", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected String prescriber;
    @XmlElement(name = "AdministeredProduct", namespace = "urn:be:cin:mycarenet:1.0:carenet:types", required = true)
    protected String administeredProduct;
    @XmlAttribute(name = "type", required = true)
    protected SpecificTechnicalCareTypeType type;

    /**
     * Gets the value of the nurseReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNurseReference() {
        return nurseReference;
    }

    /**
     * Sets the value of the nurseReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNurseReference(String value) {
        this.nurseReference = value;
    }

    /**
     * Gets the value of the requester property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequester() {
        return requester;
    }

    /**
     * Sets the value of the requester property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequester(String value) {
        this.requester = value;
    }

    /**
     * Gets the value of the treatmentPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodType }
     *     
     */
    public PeriodType getTreatmentPeriod() {
        return treatmentPeriod;
    }

    /**
     * Sets the value of the treatmentPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodType }
     *     
     */
    public void setTreatmentPeriod(PeriodType value) {
        this.treatmentPeriod = value;
    }

    /**
     * Gets the value of the prescriber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrescriber() {
        return prescriber;
    }

    /**
     * Sets the value of the prescriber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrescriber(String value) {
        this.prescriber = value;
    }

    /**
     * Gets the value of the administeredProduct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdministeredProduct() {
        return administeredProduct;
    }

    /**
     * Sets the value of the administeredProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdministeredProduct(String value) {
        this.administeredProduct = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link SpecificTechnicalCareTypeType }
     *     
     */
    public SpecificTechnicalCareTypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecificTechnicalCareTypeType }
     *     
     */
    public void setType(SpecificTechnicalCareTypeType value) {
        this.type = value;
    }

}
