//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.16 at 10:40:22 AM CEST 
//


package org.taktik.connector.business.medadminurses.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ToiletsFrequencyType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ToiletsFrequencyType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="day"/>
 *     &lt;enumeration value="week"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ToiletsFrequencyType", namespace = "urn:be:cin:mycarenet:1.0:carenet:types")
@XmlEnum
public enum ToiletsFrequencyType {

    @XmlEnumValue("day")
    DAY("day"),
    @XmlEnumValue("week")
    WEEK("week");
    private final String value;

    ToiletsFrequencyType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ToiletsFrequencyType fromValue(String v) {
        for (ToiletsFrequencyType c: ToiletsFrequencyType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
