//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.04.28 at 11:20:57 AM CEST
//
package org.taktik.freehealth.middleware.dto.recipe

import be.recipe.services.core.StatusType
import org.taktik.freehealth.middleware.domain.recipe.Prescription

class ListStructuredPrescriptionsResult(
    var status: StatusType? = null,
    var id: String? = null,
    var partial: StructuredPartial? = null
)

class StructuredPartial(
    var prescriptions: List<StructuredPrescription>? = null,
    var hasHidden: Boolean = false,
    var hasMoreResults: Boolean = false
)

