//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.04.28 at 11:20:57 AM CEST
//


package be.recipe.services.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrescriptionSortedBy complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PrescriptionSortedBy">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sortedBy" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="attribute" use="required" type="{http:/services.recipe.be/core}PrescriptionAttribute" />
 *                 &lt;attribute name="order" use="required" type="{http:/services.recipe.be/core}sortOrder" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrescriptionSortedBy", propOrder = {
    "sortedBies"
})
public class PrescriptionSortedBy {

    @XmlElement(name = "sortedBy", required = true)
    protected List<SortedBy> sortedBies;

    /**
     * Gets the value of the sortedBies property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sortedBies property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSortedBies().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SortedBy }
     *
     *
     */
    public List<SortedBy> getSortedBies() {
        if (sortedBies == null) {
            sortedBies = new ArrayList<SortedBy>();
        }
        return this.sortedBies;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="attribute" use="required" type="{http:/services.recipe.be/core}PrescriptionAttribute" />
     *       &lt;attribute name="order" use="required" type="{http:/services.recipe.be/core}sortOrder" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SortedBy {

        @XmlAttribute(name = "attribute", required = true)
        protected PrescriptionAttribute attribute;
        @XmlAttribute(name = "order", required = true)
        protected SortOrder order;

        /**
         * Gets the value of the attribute property.
         *
         * @return
         *     possible object is
         *     {@link PrescriptionAttribute }
         *
         */
        public PrescriptionAttribute getAttribute() {
            return attribute;
        }

        /**
         * Sets the value of the attribute property.
         *
         * @param value
         *     allowed object is
         *     {@link PrescriptionAttribute }
         *
         */
        public void setAttribute(PrescriptionAttribute value) {
            this.attribute = value;
        }

        /**
         * Gets the value of the order property.
         *
         * @return
         *     possible object is
         *     {@link SortOrder }
         *
         */
        public SortOrder getOrder() {
            return order;
        }

        /**
         * Sets the value of the order property.
         *
         * @param value
         *     allowed object is
         *     {@link SortOrder }
         *
         */
        public void setOrder(SortOrder value) {
            this.order = value;
        }

    }

}
