//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.28 at 11:20:57 AM CEST 
//


package be.recipe.services.core;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VisionOtherPrescribers.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="VisionOtherPrescribers">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="open"/>
 *     &lt;enumeration value="locked"/>
 *     &lt;enumeration value="gmd_prescriber"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "VisionOtherPrescribers")
@XmlEnum
public enum VisionOtherPrescribers {

    @XmlEnumValue("open")
    OPEN("open"),
    @XmlEnumValue("locked")
    LOCKED("locked"),
    @XmlEnumValue("gmd_prescriber")
    GMD_PRESCRIBER("gmd_prescriber");
    private final String value;

    VisionOtherPrescribers(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VisionOtherPrescribers fromValue(String v) {
        for (VisionOtherPrescribers c: VisionOtherPrescribers.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
