//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.04.28 at 11:20:57 AM CEST
//


package be.recipe.services.core;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VisionType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="VisionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="prescriber"/>
 *     &lt;enumeration value="executor"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "VisionType")
@XmlEnum
public enum VisionType {

    @XmlEnumValue("prescriber")
    PRESCRIBER("prescriber"),
    @XmlEnumValue("executor")
    EXECUTOR("executor");
    private final String value;

    VisionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VisionType fromValue(String v) {
        for (VisionType c: VisionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
