//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.04.28 at 11:20:57 AM CEST
//


package be.recipe.services.prescriber;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import be.recipe.services.core.VisionOtherPrescribers;


/**
 * <p>Java class for createPrescriptionParam complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="createPrescriptionParam">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="patientId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="prescription" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="prescriptionType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="feedbackRequested" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="keyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="symmKey" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="prescriberLabel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="expirationDate" type="{http:/services.recipe.be/core}LocalDate"/>
 *         &lt;element name="vision" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="visionOtherPrescribers" type="{http:/services.recipe.be/core}VisionOtherPrescribers" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createPrescriptionParam", propOrder = {

})
@XmlRootElement(name = "createPrescriptionParam")
public class CreatePrescriptionParam {

   @XmlElement(required = true)
   protected String patientId;
   @XmlElement(required = true)
   protected byte[] prescription;
   @XmlElement(required = true)
   protected String prescriptionType;
   protected boolean feedbackRequested;
   @XmlElement(required = true)
   protected String keyId;
   @XmlElement(required = true)
   protected byte[] symmKey;
   protected String prescriberLabel;
   @XmlElement(required = true)
   protected String expirationDate;
   protected String vision;
   protected VisionOtherPrescribers visionOtherPrescribers;

   /**
    * Gets the value of the patientId property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public String getPatientId() {
      return patientId;
   }

   /**
    * Sets the value of the patientId property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setPatientId(String value) {
      this.patientId = value;
   }

   /**
    * Gets the value of the prescription property.
    *
    * @return
    *     possible object is
    *     byte[]
    */
   public byte[] getPrescription() {
      return prescription;
   }

   /**
    * Sets the value of the prescription property.
    *
    * @param value
    *     allowed object is
    *     byte[]
    */
   public void setPrescription(byte[] value) {
      this.prescription = value;
   }

   /**
    * Gets the value of the prescriptionType property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public String getPrescriptionType() {
      return prescriptionType;
   }

   /**
    * Sets the value of the prescriptionType property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setPrescriptionType(String value) {
      this.prescriptionType = value;
   }

   /**
    * Gets the value of the feedbackRequested property.
    *
    */
   public boolean isFeedbackRequested() {
      return feedbackRequested;
   }

   /**
    * Sets the value of the feedbackRequested property.
    *
    */
   public void setFeedbackRequested(boolean value) {
      this.feedbackRequested = value;
   }

   /**
    * Gets the value of the keyId property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public String getKeyId() {
      return keyId;
   }

   /**
    * Sets the value of the keyId property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setKeyId(String value) {
      this.keyId = value;
   }

   /**
    * Gets the value of the symmKey property.
    *
    * @return
    *     possible object is
    *     byte[]
    */
   public byte[] getSymmKey() {
      return symmKey;
   }

   /**
    * Sets the value of the symmKey property.
    *
    * @param value
    *     allowed object is
    *     byte[]
    */
   public void setSymmKey(byte[] value) {
      this.symmKey = value;
   }

   /**
    * Gets the value of the prescriberLabel property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public String getPrescriberLabel() {
      return prescriberLabel;
   }

   /**
    * Sets the value of the prescriberLabel property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setPrescriberLabel(String value) {
      this.prescriberLabel = value;
   }

   /**
    * Gets the value of the expirationDate property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public String getExpirationDate() {
      return expirationDate;
   }

   /**
    * Sets the value of the expirationDate property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setExpirationDate(String value) {
      this.expirationDate = value;
   }

   /**
    * Gets the value of the vision property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public String getVision() {
      return vision;
   }

   /**
    * Sets the value of the vision property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setVision(String value) {
      this.vision = value;
   }

   /**
    * Gets the value of the visionOtherPrescribers property.
    *
    * @return
    *     possible object is
    *     {@link VisionOtherPrescribers }
    *
    */
   public VisionOtherPrescribers getVisionOtherPrescribers() {
      return visionOtherPrescribers;
   }

   /**
    * Sets the value of the visionOtherPrescribers property.
    *
    * @param value
    *     allowed object is
    *     {@link VisionOtherPrescribers }
    *
    */
   public void setVisionOtherPrescribers(VisionOtherPrescribers value) {
      this.visionOtherPrescribers = value;
   }

}
