//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.04.28 at 11:20:57 AM CEST
//


package be.recipe.services.prescriber;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import be.recipe.services.core.Between;
import be.recipe.services.core.Page;
import be.recipe.services.core.PrescriptionSortedBy;
import be.recipe.services.core.PrescriptionStatus;


/**
 * <p>Java class for listPrescriptionsParam complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="listPrescriptionsParam">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="symmKey" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="patientId" type="{http:/services.recipe.be/core}SSIN" minOccurs="0"/>
 *         &lt;element name="status" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="status" type="{http:/services.recipe.be/core}prescriptionStatus" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="between" type="{http:/services.recipe.be/core}Between" minOccurs="0"/>
 *         &lt;element name="expiringBetween" type="{http:/services.recipe.be/core}Between" minOccurs="0"/>
 *         &lt;element name="prescriberId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="page" type="{http:/services.recipe.be/core}Page" minOccurs="0"/>
 *         &lt;element name="sortOptions" type="{http:/services.recipe.be/core}PrescriptionSortedBy" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listPrescriptionsParam", propOrder = {

})
@XmlRootElement(name = "listPrescriptionsParam")
public class ListPrescriptionsParam {

   @XmlElement(required = true)
   protected byte[] symmKey;
   protected String patientId;
   protected ListPrescriptionsParam.Status status;
   protected Between between;
   protected Between expiringBetween;
   protected String prescriberId;
   protected Page page;
   protected PrescriptionSortedBy sortOptions;

   /**
    * Gets the value of the symmKey property.
    *
    * @return
    *     possible object is
    *     byte[]
    */
   public byte[] getSymmKey() {
      return symmKey;
   }

   /**
    * Sets the value of the symmKey property.
    *
    * @param value
    *     allowed object is
    *     byte[]
    */
   public void setSymmKey(byte[] value) {
      this.symmKey = value;
   }

   /**
    * Gets the value of the patientId property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public String getPatientId() {
      return patientId;
   }

   /**
    * Sets the value of the patientId property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setPatientId(String value) {
      this.patientId = value;
   }

   /**
    * Gets the value of the status property.
    *
    * @return
    *     possible object is
    *     {@link ListPrescriptionsParam.Status }
    *
    */
   public ListPrescriptionsParam.Status getStatus() {
      return status;
   }

   /**
    * Sets the value of the status property.
    *
    * @param value
    *     allowed object is
    *     {@link ListPrescriptionsParam.Status }
    *
    */
   public void setStatus(ListPrescriptionsParam.Status value) {
      this.status = value;
   }

   /**
    * Gets the value of the between property.
    *
    * @return
    *     possible object is
    *     {@link Between }
    *
    */
   public Between getBetween() {
      return between;
   }

   /**
    * Sets the value of the between property.
    *
    * @param value
    *     allowed object is
    *     {@link Between }
    *
    */
   public void setBetween(Between value) {
      this.between = value;
   }

   /**
    * Gets the value of the expiringBetween property.
    *
    * @return
    *     possible object is
    *     {@link Between }
    *
    */
   public Between getExpiringBetween() {
      return expiringBetween;
   }

   /**
    * Sets the value of the expiringBetween property.
    *
    * @param value
    *     allowed object is
    *     {@link Between }
    *
    */
   public void setExpiringBetween(Between value) {
      this.expiringBetween = value;
   }

   /**
    * Gets the value of the prescriberId property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public String getPrescriberId() {
      return prescriberId;
   }

   /**
    * Sets the value of the prescriberId property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setPrescriberId(String value) {
      this.prescriberId = value;
   }

   /**
    * Gets the value of the page property.
    *
    * @return
    *     possible object is
    *     {@link Page }
    *
    */
   public Page getPage() {
      return page;
   }

   /**
    * Sets the value of the page property.
    *
    * @param value
    *     allowed object is
    *     {@link Page }
    *
    */
   public void setPage(Page value) {
      this.page = value;
   }

   /**
    * Gets the value of the sortOptions property.
    *
    * @return
    *     possible object is
    *     {@link PrescriptionSortedBy }
    *
    */
   public PrescriptionSortedBy getSortOptions() {
      return sortOptions;
   }

   /**
    * Sets the value of the sortOptions property.
    *
    * @param value
    *     allowed object is
    *     {@link PrescriptionSortedBy }
    *
    */
   public void setSortOptions(PrescriptionSortedBy value) {
      this.sortOptions = value;
   }


   /**
    * <p>Java class for anonymous complex type.
    *
    * <p>The following schema fragment specifies the expected content contained within this class.
    *
    * <pre>
    * &lt;complexType>
    *   &lt;complexContent>
    *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
    *       &lt;sequence>
    *         &lt;element name="status" type="{http:/services.recipe.be/core}prescriptionStatus" maxOccurs="unbounded"/>
    *       &lt;/sequence>
    *     &lt;/restriction>
    *   &lt;/complexContent>
    * &lt;/complexType>
    * </pre>
    *
    *
    */
   @XmlAccessorType(XmlAccessType.FIELD)
   @XmlType(name = "", propOrder = {
           "statuses"
   })
   public static class Status {

      @XmlElement(name = "status", required = true)
      protected List<PrescriptionStatus> statuses;

      /**
       * Gets the value of the statuses property.
       *
       * <p>
       * This accessor method returns a reference to the live list,
       * not a snapshot. Therefore any modification you make to the
       * returned list will be present inside the JAXB object.
       * This is why there is not a <CODE>set</CODE> method for the statuses property.
       *
       * <p>
       * For example, to add a new item, do as follows:
       * <pre>
       *    getStatuses().add(newItem);
       * </pre>
       *
       *
       * <p>
       * Objects of the following type(s) are allowed in the list
       * {@link PrescriptionStatus }
       *
       *
       */
      public List<PrescriptionStatus> getStatuses() {
         if (statuses == null) {
            statuses = new ArrayList<PrescriptionStatus>();
         }
         return this.statuses;
      }

   }

}
