steps:
    -   name: 'gcr.io/cloud-builders/git'
        entrypoint: 'bash'
        args: [ '-c', 'git fetch --unshallow --tags && git checkout ${BRANCH_NAME}' ]

    -   name: 'gcr.io/cloud-builders/docker'
        args: ['login', 'docker.taktik.be', '--username', '${_REPO_USERNAME}', '--password', '${_REPO_PASSWORD}']

    -   name: 'gcr.io/cloud-builders/javac' # java + docker
        entrypoint: 'bash'
        args: [ '-c', './gradlew :dockerize -x test -PdockerPush' ]

options:
    pool:
        name: "projects/taktik-dev/locations/europe-west1/workerPools/taktik-gcb-large-pool"
timeout: 2700s
